137 specify date for sdr data
ONEcampaign/bblocks pull request #139
Opened 2022-11-08 17:38 UTC by lpicci96

- move sdr to its own module
- reformat SDR class to get specific date
- reformat function to get exchange rate
Closes #137

2022-11-09 15:02 UTC, jm-rivera requested changes
The response objects would be best stored as an html file on the test folder, and then you can read them to do all this testing. 
The file also needs formatting

2022-11-14 10:13 UTC, jm-rivera commented
@lpicci96 is this ready for a new review?

2022-11-14 10:15 UTC, lpicci96 commented
ready for review

2022-11-16 14:15 UTC, jm-rivera approved these changes

2022-11-16 14:16 UTC, merged