184 integrate new imf reader
ONEcampaign/bblocks pull request #185
Opened 2024-06-21 10:12 UTC by lpicci96

Remove old functionality and replace with `imf-reader` package

2024-06-26 09:14 UTC, lpicci96 commented
@jm-rivera

2024-06-26 10:00 UTC, jm-rivera requested changes

2024-06-26 10:00 UTC, jm-rivera commented on bblocks/import_tools/imf.py
I don't see any functionality to save the file. That would make offline uses of this tool impossible.
We need to implement a way for feather or parquet to be saved to the raw data folder (like it was with the previous weo-reader approach).

2024-06-26 14:11 UTC, lpicci96 commented on bblocks/import_tools/imf_weo.py
Added back but it would be good to know if it is used anywhere. In theory it should only have been used as a helper class for the main IMF importer

2024-07-05 16:40 UTC, lpicci96 commented
@jm-rivera back to you for review

2024-07-10 09:25 UTC, jm-rivera commented on bblocks/import_tools/imf.py
Sorry to only come back to this now. 
The current implementation only retrieves data on disk if versions are specified. I see that the challenge is that you're checking the latest version by using the reader package.

That package has `gen_latest_version` which should allow you to generate the latest version when its not provided. You could use that to try to read the latest version from disk. That would mean modifying where you are checking that the file exists, since right now you only do it if both year and version are `None`.

Here's my suggestion

```python
    def __load_data(self) -> None:
        """loading WEO as a clean dataframe

        Args:
            latest_y: passed only optional to override the behaviour to get the latest
            release year for the WEO.
            latest_r: passed only optionally to override the behaviour to get the latest
            released value (1 or 2).
        """

        names = {
            "CONCEPT_CODE": "indicator",
            "CONCEPT_LABEL": "indicator_name",
            "UNIT_LABEL": "units",
            "SCALE_LABEL": "scale",
            "LASTACTUALDATE": "estimates_start_after",
            "OBS_VALUE": "value",
            "TIME_PERIOD": "year",
            "REF_AREA_LABEL": "entity_name",
        }

        # If year and release are not specified, get the latest version
        if self.year is None and self.release is None:
            version = gen_latest_version()
            self.release, self.year = version

        # For compatibility, if the version is provided as int, convert
        if self.release == 1:
            version = ("April", self.year)
        elif self.release == 2:
            version = ("October", self.year)

        # Define the path where the data will be stored (or should be stored)
        path = f"{config.BBPaths.raw_data}/weo_{self.year}_{self.release}.feather"

        # try read from disk
        if os.path.exists(path):
            self._raw_data = pd.read_feather(path)
            return

        # If not found, fetch the data
        df = weo.fetch_data(version=version)
        
        # Check if the fetched version is the same as the requested version
        fetched_version = weo.fetch_data.last_version_fetched
        if fetched_version != version:
            self.release, self.year = version
            path = f"{config.BBPaths.raw_data}/weo_{self.year}_{self.release}.feather"

        # Load _data into _data object
        self._raw_data = (
            df.loc[:, names.keys()]
            .rename(columns=names)
            .assign(year=lambda d: convert_to_datetime(d.year))
            .assign(iso_code=lambda d: convert_id(d.entity_name, not_found=np.NaN))
            .dropna(subset=["iso_code"])
            .dropna(subset=["value"])
            .reset_index(drop=True)
        )

        # save data to disk`
        self._raw_data.to_feather(path)
```

2024-07-10 09:26 UTC, jm-rivera commented on bblocks/import_tools/imf.py
@lpicci96 I'll commit the above to this branch. Please review and if you're happy with it, let me know so I approve and merge.

2024-07-23 09:36 UTC, jm-rivera commented on bblocks/import_tools/imf.py
@lpicci96 didn't hear back, so doing it!

2024-07-23 09:36 UTC, merged